name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  packages: write

env:
  GO_VERSION: '1.24'
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test:
    name: Test and Build
    runs-on: [self-hosted, Linux, ARM64]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Download dependencies
      run: go mod download

    - name: Run tests
      run: go test ./... -v

    - name: Build installer
      run: go build -o bin/installer ./installer

    - name: Test export functionality
      run: |
        # Test that export works without kubernetes config
        ./bin/installer -conf ./installer.yaml export securedcluster > /dev/null
        echo "Export test passed"

    - name: Upload binary artifact
      uses: actions/upload-artifact@v4
      with:
        name: installer-binary
        path: bin/installer

  docker:
    name: Build and Push ARM64 Docker Image
    runs-on: [self-hosted, Linux, ARM64]
    needs: test
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Container Registry (Podman)
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | podman login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=sha,prefix=sha-

    - name: Build and push ARM64 image (Podman)
      run: |
        # Create nodocker file to quiet podman emulation message
        sudo mkdir -p /etc/containers
        sudo touch /etc/containers/nodocker
        
        # Build image with podman
        TAGS="${{ steps.meta.outputs.tags }}"
        FIRST_TAG=$(echo "$TAGS" | head -n1)
        
        podman build --platform linux/arm64 -t "$FIRST_TAG" .
        
        # Tag with all metadata tags
        while IFS= read -r tag; do
          if [ "$tag" != "$FIRST_TAG" ]; then
            podman tag "$FIRST_TAG" "$tag"
          fi
        done <<< "$TAGS"
        
        # Push all tags
        while IFS= read -r tag; do
          podman push "$tag"
        done <<< "$TAGS"

  validate-image:
    name: Validate Docker Image
    runs-on: ubuntu-latest
    needs: docker
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
    steps:
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=sha,prefix=sha-

    - name: Test Docker image
      run: |
        # Get the first tag from the metadata
        IMAGE_TAG=$(echo "${{ steps.meta.outputs.tags }}" | head -n1)
        echo "Testing image: $IMAGE_TAG"
        
        # Test help command
        docker run --rm $IMAGE_TAG --help
        
        # Test version/basic functionality
        docker run --rm $IMAGE_TAG export --help || true
        
        echo "Docker image validation passed"
